config/routes.rb
Rails.application.routes.draw do

  root :to => 'public#index'

  get 'show/:permalink', :to => 'public#show', :as => 'public_show'

  get 'admin', :to => 'access#menu'
  get 'access/menu'
  get 'access/login'
  post 'access/attempt_login'
  get 'access/logout'

  resources :admin_users, :except => [:show] do
    member do
      get :delete
    end
  end

  resources :subjects do
    member do
      get :delete
    end
  end

  resources :pages do
    member do
      get :delete
    end
  end

  resources :sections do
    member do
      get :delete
    end
  end

  get 'demo/index'
  get 'demo/hello'
  get 'demo/other_hello'
  get 'demo/lynda'
  get 'demo/escape_output'

  # default route
  # may go away in future versions of Rails
  # get ':controller(/:action(/:id))'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/views/pages/_form.html.erb
<%= error_messages_for(f.object) %>

<table summary="Page form fields">
  <tr>
    <th>Name</th>
    <td><%= f.text_field(:name) %></td>
  </tr>
  <tr>
    <th>Subject</th>
    <td><%= f.object.subject.name %></td>
  </tr>
  <tr>
    <th>Permalink</th>
    <td><%= f.text_field(:permalink) %></td>
  </tr>
  <tr>
    <th>Position</th>
    <td><%= f.select(:position, 1..@page_count) %></td>
  </tr>
  <tr>
    <th>Visible</th>
    <td><%= f.check_box(:visible) %></td>
  </tr>
</table>

app/views/pages/delete.html.erb
<% @page_title = "Delete Page" %>

<%= link_to("<< Back to List", pages_path(:subject_id => @subject.id), :class => 'back-link') %>

<div class="pages delete">
  <h2>Delete Page</h2>

  <%= form_for(@page, :url => page_path(@page, :subject_id => @subject.id), :method => 'delete') do |f| %>

    <p>Are you sure you want to permanently delete this page?</p>

    <p class="reference-name"><%= f.object.name %></p>

    <div class="form-buttons">
      <%= f.submit("Delete Page") %>
    </div>

  <% end %>
</div>

app/views/pages/edit.html.erb
<% @page_title = "Edit Page" %>

<%= link_to("<< Back to List", pages_path(:subject_id => @subject.id), :class => 'back-link') %>

<div class="pages edit">
  <h2>Update Page</h2>

  <%= form_for(@page, :url => page_path(@page, :subject_id => @subject.id)) do |f| %>

    <%= render(:partial => 'form', :locals => {:f => f}) %>

    <div class="form-buttons">
      <%= f.submit("Update Page") %>
    </div>

  <% end %>
</div>

app/views/pages/index.html.erb
<% @page_title = "All Pages" %>

<%= link_to("<< Back to Subjects", subjects_path, :class => 'back-link') %>

<div class="pages index">
  <h2>Pages</h2>

  <%= link_to("Add New Page", new_page_path(:subject_id => @subject.id), :class => 'action new') %>

  <table class="listing" summary="Page list">
    <tr class="header">
      <th>#</th>
      <th>Subject ID</th>
      <th>Page</th>
      <th>Permalink</th>
      <th>Visible</th>
      <th>Sections</th>
      <th>Actions</th>
    </tr>
    <% @pages.each do |page| %>
    <tr>
      <td><%= page.position %></td>
      <td><%= page.subject_id %></td>
      <td><%= page.name %></td>
      <td><%= page.permalink %></td>
      <td class="center"><%= status_tag(page.visible) %></td>
      <td class="center"><%= page.sections.size %></td>
      <td class="actions">
        <%= link_to("View Sections", sections_path(:page_id => page.id), :class => 'action show') %>
        <%= link_to("Show", page_path(page, :subject_id => @subject.id), :class => 'action show') %>
        <%= link_to("Edit", edit_page_path(page, :subject_id => @subject.id), :class => 'action edit') %>
        <%= link_to("Delete", delete_page_path(page, :subject_id => @subject.id), :class => 'action delete') %>
      </td>
    </tr>
    <% end %>
  </table>
</div>

app/views/pages/new.html.erb
<% @page_title = "New Page" %>

<%= link_to("<< Back to List", pages_path(:subject_id => @subject.id), :class => 'back-link') %>

<div class="pages new">
  <h2>Create Page</h2>

  <%= form_for(@page, :url => pages_path(:subject_id => @subject.id)) do |f| %>

    <%= render(:partial => 'form', :locals => {:f => f}) %>

    <div class="form-buttons">
      <%= f.submit("Create Page") %>
    </div>

  <% end %>
</div>

app/views/pages/show.html.erb
<% @page_title = "Show Page" %>

<%= link_to("<< Back to List", pages_path(:subject_id => @subject.id), :class => 'back-link') %>

<div class="pages show">
  <h2>Show Page</h2>

  <table summary="Page detail view">
    <tr>
      <th>Name</th>
      <td><%= @page.name %></td>
    </tr>
    <tr>
      <th>Subject ID</th>
      <td><%= @page.subject_id %></td>
    </tr>
    <tr>
      <th>Permalink</th>
      <td><%= @page.permalink %></td>
    </tr>
    <tr>
      <th>Position</th>
      <td><%= @page.position %></td>
    </tr>
    <tr>
      <th>Visible?</th>
      <td><%= @page.visible ? 'true' : 'false' %></td>
    </tr>
    <tr>
      <th>Created</th>
      <td><%= @page.created_at %></td>
    </tr>
    <tr>
      <th>Updated</th>
      <td><%= @page.updated_at %></td>
    </tr>
  </table>

</div>