config/routes.rb
Rails.application.routes.draw do

  root :to => 'public#index'

  get 'show/:permalink', :to => 'public#show', :as => 'public_show'

  get 'admin', :to => 'access#menu'
  get 'access/menu'
  get 'access/login'
  post 'access/attempt_login'
  get 'access/logout'

  resources :admin_users, :except => [:show] do
    member do
      get :delete
    end
  end

  resources :subjects do
    member do
      get :delete
    end
  end

  resources :pages do
    member do
      get :delete
    end
  end

  resources :sections do
    member do
      get :delete
    end
  end

  get 'demo/index'
  get 'demo/hello'
  get 'demo/other_hello'
  get 'demo/lynda'
  get 'demo/escape_output'

  # default route
  # may go away in future versions of Rails
  # get ':controller(/:action(/:id))'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/admin_user.rb
class AdminUser < ApplicationRecord

  # self.table_name = "admin_users"

  has_secure_password

  has_and_belongs_to_many :pages
  has_many :section_edits
  has_many :sections, :through => :section_edits

  EMAIL_REGEX = /\A[a-z0-9._%+-]+@[a-z0-9.-]+\.[a-z]{2,4}\Z/i
  FORBIDDEN_USERNAMES = ['littlebopeep','humptydumpty','marymary']

  # "long form" validations
  # validates_presence_of :first_name
  # validates_length_of :first_name, :maximum => 25
  # validates_presence_of :last_name
  # validates_length_of :last_name, :maximum => 50
  # validates_presence_of :username
  # validates_length_of :username, :within => 8..25
  # validates_uniqueness_of :username
  # validates_presence_of :email
  # validates_length_of :email, :maximum => 100
  # validates_format_of :email, :with => EMAIL_REGEX
  # validates_confirmation_of :email

  # "sexy" validations
  validates :first_name, :presence => true,
												 :length => { :maximum => 25 }
  validates :last_name, :presence => true,
                        :length => { :maximum => 50 }
  validates :username, :length => { :within => 8..25 },
                       :uniqueness => true
  validates :email, :presence => true,
                    :length => { :maximum => 100 },
                    :format => EMAIL_REGEX,
                    :confirmation => true

  validate :username_is_allowed
  validate :no_new_users_on_monday, :on => :create

  scope :sorted, lambda { order('last_name ASC, first_name ASC')}

  def name
    "#{first_name} #{last_name}"
    # Or: first_name + ' ' + last_name
    # Or: [first_name, last_name].join(' ')
  end

  private

  def username_is_allowed
    if FORBIDDEN_USERNAMES.include?(username)
      errors.add(:username, "has been restricted from use.")
    end
  end

  def no_new_users_on_monday
    if Time.now.wday == 1
      errors.add(:base, "No new users on Mondays.")
    end
  end

end

app/controllers/admin_users_controller.rb
class AdminUsersController < ApplicationController

  layout 'admin'

  before_action :confirm_logged_in

  def index
    @admin_users = AdminUser.sorted
  end

  def new
    @admin_user = AdminUser.new
  end

  def create
    @admin_user = AdminUser.new(admin_user_params)
    if @admin_user.save
      flash[:notice] = 'Admin user created successfully.'
      redirect_to(admin_users_path)
    else
      render('new')
    end
  end

  def edit
    @admin_user = AdminUser.find(params[:id])
  end

  def update
    @admin_user = AdminUser.find(params[:id])
    if @admin_user.update_attributes(admin_user_params)
      flash[:notice] = 'Admin user updated successfully.'
      redirect_to(admin_users_path)
    else
      render('edit')
    end
  end

  def delete
    @admin_user = AdminUser.find(params[:id])
  end

  def destroy
    @admin_user = AdminUser.find(params[:id])
    @admin_user.destroy
    flash[:notice] = "Admin user destroyed successfully."
    redirect_to(admin_users_path)
  end

  private

  def admin_user_params
    # Permit :password, but NOT :password_digest
    params.require(:admin_user).permit(
      :first_name,
      :last_name,
      :email,
      :username,
      :password
    )
  end

end

app/helpers/admin_users_helper.rb
module AdminUsersHelper
end

app/views/admin_users/_form.html.erb
<%= error_messages_for(f.object) %>

<table summary="Admin user form fields">
  <tr>
    <th><%= f.label(:first_name) %></th>
    <td><%= f.text_field(:first_name) %></td>
  </tr>
  <tr>
    <th><%= f.label(:last_name) %></th>
    <td><%= f.text_field(:last_name) %></td>
  </tr>
  <tr>
    <th><%= f.label(:email) %></th>
    <td><%= f.text_field(:email) %></td>
  </tr>
  <tr>
    <th><%= f.label(:username) %></th>
    <td><%= f.text_field(:username) %></td>
  </tr>
  <tr>
    <th><%= f.label(:password) %></th>
    <td><%= f.password_field(:password) %></td>
  </tr>
</table>

app/views/admin_users/delete.html.erb
<% @page_title = "Delete Admin User" %>

<%= link_to("<< Back to List", admin_users_path, :class => 'back-link') %>

<div class="admin-users delete">
  <h2>Delete Admin User</h2>

  <%= form_for(@admin_user, :method => 'delete') do |f| %>

    <p>Are you sure you want to permanently delete this admin user?</p>

    <p class="reference-name"><%= f.object.name %></p>

    <div class="form-buttons">
      <%= f.submit("Delete Admin User") %>
    </div>

  <% end %>
</div>

app/views/admin_users/edit.html.erb
<% @page_title = "Update Admin User" %>

<%= link_to("<< Back to List", admin_users_path, :class => 'back-link') %>

<div class="admin-users edit">
  <h2>Update Admin User</h2>

  <%= form_for(@admin_user) do |f| %>

    <%= render(:partial => 'form', :locals => {:f => f}) %>

    <div class="form-buttons">
      <%= f.submit("Update Admin User") %>
    </div>

  <% end %>
</div>

app/views/admin_users/index.html.erb
<% @page_title = "All Admin Users" %>

<%= link_to("<< Back to Menu", admin_path, :class => 'back-link') %>

<div class="admin-users index">
  <h2>Admin Users</h2>

  <%= link_to('Add New Admin User', new_admin_user_path, :class => 'action new') %>

  <div><%= pluralize(@admin_users.size, 'admin user') %> found</div>

  <table class="listing" summary="Admin users list">
    <tr>
      <th>Username</th>
      <th>Name</th>
      <th>Email</th>
      <th>Actions</th>
    </tr>
    <% @admin_users.each do |admin_user| %>
    <tr>
      <td><%= admin_user.username %></td>
      <td><%= admin_user.name %></td>
      <td><%= mail_to(admin_user.email) %></td>
      <td class="actions">
        <%= link_to('Edit', edit_admin_user_path(admin_user), :class => 'action edit') %>
        <%= link_to('Delete', delete_admin_user_path(admin_user), :class => 'action delete') %>
      </td>
    </tr>
    <% end %>
  </table>

</div>

app/views/admin_users/new.html.erb
<% @page_title = "New Admin User" %>

<%= link_to("<< Back to List", admin_users_path, :class => 'back-link') %>

<div class="admin-users new">
  <h2>Create Admin User</h2>

  <%= form_for(@admin_user) do |f| %>

    <%= render(:partial => 'form', :locals => {:f => f}) %>

    <div class="form-buttons">
      <%= f.submit("Create Admin User") %>
    </div>

  <% end %>
</div>